import { Course, CourseDetail } from './types';

export const mockCourses: Course[] = [
  {
    id: 1,
    title: '주식 초보자를 위한 기초 강좌',
    description: '주식투자의 기초부터 실전 팁까지 배우는 완벽한 입문 강좌',
    category: 'DOMESTIC_STOCK',
    price: 49000,
    thumbnailUrl: '/courses/stock-basics.jpg',
    instructor: '김재훈 강사',
    rating: 4.8,
    totalEnrollments: 1250,
  },
  {
    id: 2,
    title: '비트코인과 이더리움 제대로 이해하기',
    description: '암호화폐 시장의 핵심을 파악하고 투자 전략을 세우세요',
    category: 'CRYPTO',
    price: 59000,
    thumbnailUrl: '/courses/crypto-basics.jpg',
    instructor: '이규형 강사',
    rating: 4.6,
    totalEnrollments: 890,
  },
  {
    id: 3,
    title: '차트 분석 마스터 클래스',
    description: '기술적 분석을 통한 수익 창출 전략',
    category: 'DOMESTIC_STOCK',
    price: 69000,
    thumbnailUrl: '/courses/chart-analysis.jpg',
    instructor: '박준호 강사',
    rating: 4.7,
    totalEnrollments: 756,
  },
  {
    id: 4,
    title: '포트폴리오 관리 전문가 되기',
    description: '분산 투자와 리스크 관리의 정석',
    category: 'DOMESTIC_STOCK',
    price: 79000,
    thumbnailUrl: '/courses/portfolio.jpg',
    instructor: '강민지 강사',
    rating: 4.9,
    totalEnrollments: 2103,
  },
  {
    id: 5,
    title: 'DeFi 프로토콜 심화 과정',
    description: '탈중앙화 금융의 미래를 선도하는 투자자 되기',
    category: 'CRYPTO',
    price: 89000,
    thumbnailUrl: '/courses/defi.jpg',
    instructor: '최영민 강사',
    rating: 4.5,
    totalEnrollments: 432,
  },
  {
    id: 6,
    title: '배당주 투자로 장기 자산 만들기',
    description: '안정적인 현금 흐름을 위한 배당주 선택 전략',
    category: 'DOMESTIC_STOCK',
    price: 39000,
    thumbnailUrl: '/courses/dividend.jpg',
    instructor: '서재훈 강사',
    rating: 4.8,
    totalEnrollments: 1876,
  },
];

export const mockCourseDetail: Record<number, CourseDetail> = {
  1: {
    id: 1,
    title: '주식 초보자를 위한 기초 강좌',
    description:
      '주식투자의 기초부터 실전 팁까지 배우는 완벽한 입문 강좌입니다. 이 강의에서는 주식 시장의 구조, 기본 개념, 그리고 투자 전략을 명확하게 설명합니다.',
    category: 'DOMESTIC_STOCK',
    price: 49000,
    thumbnailUrl: '/courses/stock-basics.jpg',
    instructor: '김재훈 강사',
    rating: 4.8,
    totalEnrollments: 1250,
    sections: [
      {
        id: 1,
        courseId: 1,
        title: '1장: 주식의 기초 개념',
        sortOrder: 1,
        lectures: [
          {
            id: 1,
            sectionId: 1,
            title: '1-1. 주식이란 무엇인가?',
            videoUrl: 'https://example.com/video1.mp4',
            playTime: 1200,
            sortOrder: 1,
          },
          {
            id: 2,
            sectionId: 1,
            title: '1-2. 주식 시장의 구조',
            videoUrl: 'https://example.com/video2.mp4',
            playTime: 1500,
            sortOrder: 2,
          },
          {
            id: 3,
            sectionId: 1,
            title: '1-3. 기본 용어 정리',
            videoUrl: 'https://example.com/video3.mp4',
            playTime: 1800,
            sortOrder: 3,
          },
        ],
      },
      {
        id: 2,
        courseId: 1,
        title: '2장: 투자 시작하기',
        sortOrder: 2,
        lectures: [
          {
            id: 4,
            sectionId: 2,
            title: '2-1. 계좌 개설하기',
            videoUrl: 'https://example.com/video4.mp4',
            playTime: 2100,
            sortOrder: 1,
          },
          {
            id: 5,
            sectionId: 2,
            title: '2-2. 첫 주식 사기',
            videoUrl: 'https://example.com/video5.mp4',
            playTime: 1600,
            sortOrder: 2,
          },
        ],
      },
    ],
  },
  2: {
    id: 2,
    title: '비트코인과 이더리움 제대로 이해하기',
    description:
      '암호화폐 시장의 핵심을 파악하고 투자 전략을 세우세요. 블록체인의 기초부터 현물 거래까지 다룹니다.',
    category: 'CRYPTO',
    price: 59000,
    thumbnailUrl: '/courses/crypto-basics.jpg',
    instructor: '이규형 강사',
    rating: 4.6,
    totalEnrollments: 890,
    sections: [
      {
        id: 3,
        courseId: 2,
        title: '1장: 블록체인 이해하기',
        sortOrder: 1,
        lectures: [
          {
            id: 6,
            sectionId: 3,
            title: '1-1. 블록체인이란?',
            videoUrl: 'https://example.com/video6.mp4',
            playTime: 2400,
            sortOrder: 1,
          },
          {
            id: 7,
            sectionId: 3,
            title: '1-2. 암호화폐의 종류',
            videoUrl: 'https://example.com/video7.mp4',
            playTime: 1900,
            sortOrder: 2,
          },
        ],
      },
    ],
  },
  3: {
    id: 3,
    title: '차트 분석 마스터 클래스',
    description: '기술적 분석을 통한 수익 창출 전략',
    category: 'DOMESTIC_STOCK',
    price: 69000,
    thumbnailUrl: '/courses/chart-analysis.jpg',
    instructor: '박준호 강사',
    rating: 4.7,
    totalEnrollments: 756,
    sections: [
      {
        id: 4,
        courseId: 3,
        title: '1장: 차트 기초',
        sortOrder: 1,
        lectures: [
          {
            id: 8,
            sectionId: 4,
            title: '1-1. 캔들 차트 읽기',
            videoUrl: 'https://example.com/video8.mp4',
            playTime: 2200,
            sortOrder: 1,
          },
        ],
      },
    ],
  },
};

export const mockMyCoures = [
  {
    id: 1,
    courseId: 1,
    title: '주식 초보자를 위한 기초 강좌',
    thumbnailUrl: '/courses/stock-basics.jpg',
    instructor: '김재훈 강사',
    enrolledAt: '2024-03-01',
    progressPercentage: 65,
    isCompleted: false,
  },
  {
    id: 2,
    courseId: 2,
    title: '비트코인과 이더리움 제대로 이해하기',
    thumbnailUrl: '/courses/crypto-basics.jpg',
    instructor: '이규형 강사',
    enrolledAt: '2024-02-15',
    progressPercentage: 100,
    isCompleted: true,
  },
  {
    id: 3,
    courseId: 4,
    title: '포트폴리오 관리 전문가 되기',
    thumbnailUrl: '/courses/portfolio.jpg',
    instructor: '강민지 강사',
    enrolledAt: '2024-03-10',
    progressPercentage: 25,
    isCompleted: false,
  },
];
